### PR TITLE
Update system-codes.md

### PR DESCRIPTION
**Pull request by tabbassidaloii**
@DeniseSl22: Adding SystemCodes for different species.

### CODE REVIEW

**Comment by egonw** [comment]
@DeniseSl22, what do you think? Should we have this on the syscodes page or make a separate page?

**Comment by DeniseSl22** [comment]
> @DeniseSl22, what do you think? Should we have this on the syscodes page or make a separate page?

Yeah, I was thinking about splitting it up too (and make both pages point to one another). The systems codes overview we have now is relying on the datasources.tsv file/repo, while the species are defined somewhere else (I don't know exactly where though).

**Comment by tabbassidaloii** [comment]
> > @DeniseSl22, what do you think? Should we have this on the syscodes page or make a separate page?
> 
> Yeah, I was thinking about splitting it up too (and make both pages point to one another). The systems codes overview we have now is relying on the datasources.tsv file/repo, while the species are defined somewhere else (I don't know exactly where though).

species are from https://github.com/bridgedb/datasources/blob/main/organisms.tsv. Make sense to split it.

**Comment by egonw** [comment]
Okay, plz split it up. I'll close this PR.

**Pull request closed without merging**
